# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0002_auto_20160203_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='male', max_length=200),
            preserve_default=False,
        ),
    ]
