# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0003_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_accepted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_lng',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], default=b'Male', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sports',
            field=models.ManyToManyField(to='firstpick.Sport'),
        ),
    ]
