# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstpick', '0004_auto_20160203_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[(b'No preference', b'No preference'), (b'Male only', b'Male only'), (b'Female only', b'Female only')], max_length=200)),
                ('rating_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[(b'completed', b'completed'), (b'cancelled', b'cancelled'), (b'upcoming', b'upcoming')], max_length=200)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpick.Sport')),
            ],
        ),
    ]
