# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 3, 3, 11, 54, 243286, tzinfo=utc), verbose_name=b'Start time'),
            preserve_default=False,
        ),
    ]
