# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0006_auto_20160203_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='location_lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='players_needed',
            field=models.IntegerField(default=0),
        ),
    ]
