# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstpick', '0007_auto_20160203_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius', models.IntegerField(default=1)),
                ('rating_count', models.IntegerField(default=0)),
                ('rating_avg', models.FloatField(default=2.5)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpick.Sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
