# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0009_sportprofile_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sports',
        ),
    ]
