# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstpick', '0010_remove_userprofile_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players',
            field=models.ManyToManyField(default=None, related_name='Players', to=settings.AUTH_USER_MODEL),
        ),
    ]
