# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0012_event_invitees'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sports',
            field=models.ManyToManyField(default=None, to='firstpick.Sport'),
        ),
    ]
