# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0014_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='msg_type',
            field=models.CharField(choices=[(b'New Event', b'New Event'), (b'RSVP Yes', b'RSVP Yes'), (b'RSVP No', b'RSVP No'), (b'Event Changed', b'Event Changed'), (b'Event Cancelled', b'Event Cancelled')], default='New Event', max_length=200),
            preserve_default=False,
        ),
    ]
