# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0015_msg_msg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_address',
            field=models.CharField(default='address default', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='msg',
            name='datetime',
            field=models.DateTimeField(verbose_name=b'Sent at'),
        ),
    ]
