# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpick', '0017_auto_20160209_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[(b'No gender preference', b'No gender preference'), (b'Male only', b'Male only'), (b'Female only', b'Female only')], max_length=200),
        ),
    ]
